CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    access_level INTEGER NOT NULL DEFAULT 0,
    locked BOOLEAN NOT NULL DEFAULT 0,
    passcrypt VARCHAR(255)
)
